pipeline:
  build:
    image: docker
    commands:
      - docker build --rm -t hello-world .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push
  
  create-container:
    image: docker
    commands:
      - docker run -d -p 4000:80 hello-world
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push

  test-container:
    image: python
    commands:
      - pip install -r ./scripts/test-requirements.txt
      - python ./scripts/test.py
    when:
      branch: [master, development]
      event: push

  delete-container:
    image: docker
    commands:
      - sh ./scripts/rm-d.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push

  push-to-registry:
    image: plugins/docker
    repo: rhysemmas/hello-world
    secrets: [ DOCKER_USERNAME, DOCKER_PASSWORD ]
    tags: latest
    when:
      branch: master
      event: push

#  deploy-to-kube:
#    image: quay.io/ukhomeofficedigital/kd:v1.10.6
#    
#    when:
#      event: deployment
