pipeline:
  build:
    image: docker
    commands:
      - docker build --rm -t hello-world .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push
  
  test_image:
    image: docker
    commands:
      - docker run -d -p 4000:80 hello-world
      - docker ps -a | awk '{ print $1,$2 }' | grep hello-world | awk '{print $1 }' | xargs -I {} sh -c 'docker kill {}; docker rm {};'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push
