pipeline:
  build:
    image: docker
    commands:
      - docker build --rm -t hello-world .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push
  
  test_image:
    image: docker
    commands:
      - docker run -p 4000:80 hello-world -d | docker ps -a | awk '{ print $1,$2 }' | grep hello-world | awk '{print $1 }'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push
