pipeline:
  build:
    image: docker
    commands:
      - docker build --rm -t hello-world .
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push
  
  create_image:
    image: docker
    commands:
      - docker run -d -p 4000:80 hello-world
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push

  test_image:
    image: python
    commands:
      - pip install -r ./scripts/test-requirements.txt
      - python ./scripts/test.py
    when:
      branch: [master, development]
      event: push

  delete_image:
    image: docker
    commands:
      - sh ./scripts/rm-d.sh
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    when:
      branch: [master, development]
      event: push
